# Use Python base image
FROM python:3.8-slim

# Set the working directory inside the container
WORKDIR /app

# Command to run a script from the volume (this script will be provided by the volume)
CMD ["python", "/app/hello_from_volume.py"]
